name: 'gprbuild'
description: 'Build a GPR project with gprbuild'
author: 'Alejandro R. Mosteo'

inputs: 
  docker-image:
    description: 'A dockerhub image with gprbuild in its $PATH'
    default: 'alire/gnat:ubuntu-stable'

  project-file:
    description: 'GPR file to build'
    required: true

runs:
  using: 'docker'
  image: 'docker://${{ inputs.docker-image }}'
  args: [ 'gprbuild', '-p', '-P', '${{ inputs.project-file }}' ]
