name: Test Workflow

on: [pull_request, push]

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v2
      
    - name: test docker action
      uses: mosteo/actions@playground/v0
